import { Inter } from "next/font/google";
import "./globals.css";
import HeadNav from "./Components/Navber/HeadNav/HeadNav";
import Navber from "./Components/Navber/Navber/Navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <HeadNav />
        <Navber />
          {children}
        </div>
      </body>
    </html>
  );
}
